name: Build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  buf-build:
    name: Buf build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1

      - name: Build proto files
        run: buf build proto
