name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buf-publish:
    name: Publish to Buf Schema Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish proto module
        uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          push: true
          push_create_visibility: public
          lint: true
          format: false
          breaking: false
          archive: false
          pr_comment: false
