name: Release

on:
  workflow_call:

permissions:
  contents: read

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish proto module
        uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          push: true
          push_create_visibility: public
          lint: false
          format: false
          breaking: false
          archive: false
          pr_comment: false
